algo = input('Digite algo:')
print('O tipo primitivo do dado informado é {}'.format(type(algo)))
print('É um número? {}'.format(algo.isnumeric()))
print('É alfabético? {}'.format(algo.isalpha()))
print('Está completamente em maiúsculo? {}'.format(algo.isupper()))
print('Possui espaco? {}'.format(algo.isspace()))
print('Está completamente em minúsculo? {}'.format(algo.islower()))
print('É um título? {}'.format(algo.istitle()))
print('É alfanumerico? {:-^20}'.format(algo.isalnum()))
